---
- name: Clone dotfiles
  ansible.builtin.import_tasks: dotfiles.yml
  tags: dotfiles

- name: Download wallpapers
  ansible.builtin.import_tasks: wallpapers.yml
  tags: wallpapers

- name: Generate colorschemes
  ansible.builtin.import_tasks: pywal.yml
  tags: colorschemes, pywal

- name: Setup XOrg
  ansible.builtin.import_tasks: xorg.yml
  tags: xorg, x-window

- name: Setup window manager
  ansible.builtin.import_tasks: wm.yml
  tags: wm, window-manager

- name: Install fonts and icons
  ansible.builtin.import_tasks: fonts.yml
  tags: fonts, nerd-fonts

- name: Setup terminal emulator
  ansible.builtin.import_tasks: termemu.yml
  tags: terminal, terminal-emulator
- name: Install status bar
  ansible.builtin.import_tasks: polybar.yml
  tags: status-bar

- name: Setup application launcher
  ansible.builtin.import_tasks: rofi.yml
  tags: app-launcher, launcher

- name: Setup compositor
  ansible.builtin.import_tasks: picom.yml
  tags: compositor

- name: Setup notification daemon
  ansible.builtin.import_tasks: dunst.yml
  tags: notifications
