---
- name: Install app launcher
  become: true
  community.general.pacman:
    name: rofi
    state: present

- name: Move config and scripts to .config
  become: true
  become_user: "{{ username }}"
  ansible.builtin.copy:
    src: "{{ dotfiles_dir }}/rofi"
    dest: "{{ home_dir }}/.config/"
    force: true
