---
- name: Install terminal emulator
  community.general.pacman:
    name: kitty
    state: present

- name: Copy config and scripts to .config folder
  become: true
  become_user: "{{ username }}"
  ansible.builtin.copy:
    src: "{{ dotfiles_dir }}/kitty"
    dest: "{{ home_dir }}/.config/"
    force: true
