---
- name: Install networking tools
  become: true
  community.general.pacman:
    name: "{{ package }}"
  with_items: "{{ networking_tools | default(networking_tools) }}"
  loop_control:
    loop_var: package
    label: "{{ package }}"

- name: Install security tools
  become: true
  community.general.pacman:
    name: "{{ package }}"
  with_items: "{{ security_tools | default(security_tools) }}"
  loop_control:
    loop_var: package
    label: "{{ package }}"

- name: Install tools from AUR
  become: true
  become_user: "{{ username }}"
  ansible.builtin.command: "yay --noconfirm -S {{ package }}}"
  with_items: "{{ aur_tools | default(aur_tools) }}"
  loop_control:
    loop_var: package
    label: "{{ package }}"
