---
- name: "Clone dotfiles {{ dotfiles_repo_branch }} branch"
  become: true
  become_user: "{{ username }}"
  ansible.builtin.git:
    repo: "{{ dotfiles_repo_url }}"
    version: "{{ dotfiles_repo_branch }}"
    dest: "{{ dotfiles_dir }}"
    force: true

- name: Create dotconfig directory
  become: true
  become_user: "{{ username }}"
  ansible.builtin.file:
    path: "{{ home_dir }}/.config"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0744
