---
- name: User configuration
  ansible.builtin.import_tasks: user.yml
  tags: user

- name: Install packages
  ansible.builtin.import_tasks: packages.yml
  tags: packages, core, util

- name: Clone and link dotfiles
  ansible.builtin.import_tasks: dotfiles.yml
  tags: dotfiles

- name: Setup yay
  ansible.builtin.import_tasks: yay.yml
  tags: yay, aur

- name: Setup virtulabox
  ansible.builtin.import_tasks: vbox.yml
  when: is_virtualbox_installation
  tags: virtualbox

- name: Setup zsh
  ansible.builtin.import_tasks: zsh.yml
  tags: zsh

- name: Setup tmux
  ansible.builtin.import_tasks: tmux.yml
  tags: tmux

- name: Setup neovim
  ansible.builtin.import_tasks: neovim.yml
  tags: neovim
