---
- name: Install core packages from arch repos
  become: true
  community.general.pacman:
    name: "{{ package }}"
    state: present
  with_items: "{{ core_packages | default(core_packages) }}"
  loop_control:
    loop_var: package
    label: "{{ package }}"

- name: Install util packages from arch repos
  become: true
  community.general.pacman:
    name: "{{ package }}"
    state: present
  with_items: "{{ util_packages | default(util_packages) }}"
  loop_control:
    loop_var: package
    label: "{{ package }}"
